# Permalinks
permalink:           pretty

# Setup
title:               "Carlos's Home Page"
url:                 https://porter.cloud
tagline:             "Blogging about tech, books, and day to day life"
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# Cloudinary
#cloudinary:
#  cloud_name: your cloudinary username

# About/contact
author:
  name:              Carlos Williams-Moreiras
  url:               https://porter.cloud
  email:             cwmoreiras@gmail.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/cwmoreiras/cwmoreiras.github.io

gems:
- jekyll-email-protect
